sonar.projectKey=Booth-Organizer-System
sonar.projectName=Booth-Organizer-System
sonar.sources=implementations/backend/app
sonar.tests=implementations/backend/tests

sonar.python.coverage.reportPaths=implementations/backend/coverage.xml

sonar.exclusions=**/node_modules/**,**/*.js,**/*.css