sonar.projectKey=booth-organizer-system
sonar.organization=booth-organizer-system
sonar.projectName=Booth Organizer System
sonar.projectVersion=1.0
sonar.sources=implementations/backend/app
sonar.tests=implementations/backend/tests
sonar.python.coverage.reportPaths=implementations/backend/coverage.xml
sonar.exclusions=**/node_modules/**,**/build/**,**/*.css
sonar.sourceEncoding=UTF-8